sudo: required
services:
  - docker

before_install: 
  - docker build -t trestianstewart/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trestianstewart/docker-react npm run test -- --coverage --watchAll=false

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-683432915883"
  bucket_path: "dockerreact-env"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"