sudo: required
services:
  - docker

before_install: 
  - docker build -t trestianstewart/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trestianstewart/docker-react npm run test -- --coverage --watchAll=false